// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MilkTeaCashier.Data.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int EmployeeId { get; set; }

    public double TotalAmount { get; set; }

    public string Status { get; set; } 

    public string CustomerName { get; set; }

    public bool? IsStay { get; set; }

    public string Note { get; set; }

    public int? NumberTableCard { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime? CreatedAt { get; set; } 

    public DateTime? UpdatedAt { get; set; }

    public int? CustomerId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}

public enum OrderStatus
{
    Pending,
    Completed,
    Canceled
}

public enum PaymentMethodType
{
    Cash,
    Card,
    Online
}
