// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkTeaCashier.Data.Models;

public partial class TableCard
{
    public int NumberTableCard { get; set; }
}